import { useTexture } from '@react-three/drei';

const assetRoot = '/itomdev-clone';
function asset(relativePath: string) {
  return `${assetRoot}${relativePath}`;
}

export function preloadAllTextures() {
  const textures = [
    '/images/ink-splash.webp',
    '/textures/about/GSAPduzybalon.webp',
    '/textures/about/GSAPduzybalon_painted.webp',
    '/textures/about/SOTD.webp',
    '/textures/about/SOTD_painted.webp',
    '/textures/about/SOTM.webp',
    '/textures/about/SOTM_painted.webp',
    '/textures/about/SOTY.webp',
    '/textures/about/SOTY_painted.webp',
    '/textures/about/awatarnachmurce.webp',
    '/textures/about/csssrednibalon.webp',
    '/textures/about/csssrednibalon_painted.webp',
    '/textures/about/figmamalybalon.webp',
    '/textures/about/figmamalybalon_painted.webp',
    '/textures/about/firebasemalybalon.webp',
    '/textures/about/firebasemalybalon_painted.webp',
    '/textures/about/freelancewyspa.webp',
    '/textures/about/gitmalybalon.webp',
    '/textures/about/gitmalybalon_painted.webp',
    '/textures/about/htmlmalybalon.webp',
    '/textures/about/htmlmalybalon_painted.webp',
    '/textures/about/nextjssrednibalon.webp',
    '/textures/about/nextjssrednibalon_painted.webp',
    '/textures/about/reactduzybalon.webp',
    '/textures/about/reactduzybalon_painted.webp',
    '/textures/about/uowyspa.webp',
    '/textures/clouds/1131c3eb-dfae-423f-924b-ff39d8ccd6dc.webp',
    '/textures/clouds/254b8ec8-d6f7-4275-956f-7bab65b2ce2d.webp',
    '/textures/clouds/2cc88dd1-483c-466d-b07e-f8308c61ccbe.webp',
    '/textures/clouds/5606fcc0-3252-447d-a58a-7bcbac73229a.webp',
    '/textures/clouds/7882dc72-3d01-41fb-ac0e-d07b0184ebc1.webp',
    '/textures/clouds/9b2ca72f-7bd0-473b-ba6e-dd9e0eb79d35.webp',
    '/textures/clouds/c83293c6-d90c-4a32-8d9d-5ac9af7e2296.webp',
    '/textures/clouds/f6e358bc-d27c-41dd-95f4-6787a835c41e.webp',
    '/textures/corridor/ceiling_texture.webp',
    '/textures/corridor/doors/backsingledoors.webp',
    '/textures/corridor/doors/frame_sketch.webp',
    '/textures/corridor/doors/klamkadodrzwi.webp',
    '/textures/corridor/drzewkowdoniczce.webp',
    '/textures/corridor/gorastolika.webp',
    '/textures/corridor/kawalekpodlogi.webp',
    '/textures/corridor/kwiatekwdoniczce.webp',
    '/textures/corridor/pustatabliczka.webp',
    '/textures/corridor/ramkanazdjecieduza.webp',
    '/textures/corridor/ramkanazdjecieduza_painted.webp',
    '/textures/corridor/ramkanazdjeciemala.webp',
    '/textures/corridor/ramkanazdjeciemala_painted.webp',
    '/textures/corridor/rysuneknaobraz1.webp',
    '/textures/corridor/texturadoprogow.webp',
    '/textures/corridor/texturadrewnadonozekbiurka.webp',
    '/textures/corridor/wall_texture.webp',
    '/textures/doors/door_back.webp',
    '/textures/doors/door_back_left_sketch.webp',
    '/textures/doors/door_left_painted.webp',
    '/textures/doors/door_left_sketch.webp',
    '/textures/doors/door_right_painted.webp',
    '/textures/doors/door_right_sketch.webp',
    '/textures/doors/frame_sketch.webp',
    '/textures/doors/handle_left_painted.webp',
    '/textures/doors/handle_left_sketch.webp',
    '/textures/doors/handle_right_painted.webp',
    '/textures/doors/handle_right_sketch.webp',
    '/textures/doors/pien.webp',
    '/textures/entrance/avatar_window.webp',
    '/textures/entrance/belka.webp',
    '/textures/entrance/bug_sketch.webp',
    '/textures/entrance/cat_front_body.webp',
    '/textures/entrance/letterbox_painted.png',
    '/textures/entrance/letterbox_sketch.png',
    '/textures/entrance/mouse_hanging.webp',
    '/textures/entrance/pot_with_duck.webp',
    '/textures/entrance/sign.webp',
    '/textures/entrance/speech_bubble.webp',
    '/textures/entrance/stone-path.webp',
    '/textures/entrance/tree_sketch.webp',
    '/textures/entrance/wall_bricks_2.webp',
    '/textures/entrance/window_sketch.webp',
    '/textures/gallery/bird_gray.webp',
    '/textures/gallery/domki.webp',
    '/textures/gallery/floor.webp',
    '/textures/gallery/klamerka.webp',
    '/textures/gallery/miastotlo.webp',
    '/textures/gallery/railing.webp',
    '/textures/paper-texture.webp',
    '/textures/studio/Aandolan.png',
    '/textures/studio/Aandolan_painted.jpg',
    '/textures/studio/Illustration.png',
    '/textures/studio/Illustration_painted.jpg',
    '/textures/studio/Naalayak.png',
    '/textures/studio/Naalayak_painted.jpg',
    '/textures/studio/TedX.png',
    '/textures/studio/TedX_painted.jpg',
    '/textures/studio/monitor_back.webp',
    '/textures/studio/monitor_back_painted.webp',
    '/textures/studio/monitor_bottom.webp',
    '/textures/studio/monitor_bottom_painted.webp',
    '/textures/studio/monitor_front.webp',
    '/textures/studio/monitor_front_painted.webp',
    '/textures/studio/monitor_left.webp',
    '/textures/studio/monitor_left_painted.webp',
    '/textures/studio/monitor_right.webp',
    '/textures/studio/monitor_right_painted.webp',
    '/textures/studio/monitor_top.webp',
    '/textures/studio/monitor_top_painted.webp',
    '/textures/studio/phone_back.webp',
    '/textures/studio/phone_back_painted.webp',
    '/textures/studio/phone_front.webp',
    '/textures/studio/phone_front_painted.webp',
    '/textures/studio/phone_side.webp',
    '/textures/studio/phone_side_painted.webp',
    '/textures/studio/tv_back.webp',
    '/textures/studio/tv_back_painted.webp',
    '/textures/studio/tv_bottom.webp',
    '/textures/studio/tv_bottom_painted.webp',
    '/textures/studio/tv_front.webp',
    '/textures/studio/tv_front_painted.webp',
    '/textures/studio/tv_side.webp',
    '/textures/studio/tv_side_painted.webp',
    '/textures/studio/tv_top.webp',
    '/textures/studio/tv_top_painted.webp',
    '/textures/studio/tvfront_filmikprojektdlamultiego.webp',
    '/textures/studio/tvfront_filmikprojektdlamultiego_painted.webp'
  ];

  textures.forEach((path) => {
    useTexture.preload(asset(path));
  });

  // Preload the main font using a hidden dummy fetch or troika directly if available
  // Easiest is just a fetch to warm up the cache so troika doesn't suspend
  fetch('/fonts/CabinSketch-Bold.ttf').catch(() => {});
}
